"""empty message

Revision ID: 19917442f96a
Revises: 3d8ba0d9899d
Create Date: 2021-05-21 18:48:31.230161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19917442f96a'
down_revision = '3d8ba0d9899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'rental_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
