"""empty message

Revision ID: 20b20a03caaa
Revises: 19917442f96a
Create Date: 2021-05-21 20:43:44.809457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b20a03caaa'
down_revision = '19917442f96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_in')
    # ### end Alembic commands ###
