"""empty message

Revision ID: 3d8ba0d9899d
Revises: 6c58fdd17280
Create Date: 2021-05-21 18:47:34.803156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8ba0d9899d'
down_revision = '6c58fdd17280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rental', 'rental_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rental', 'rental_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
