"""empty message

Revision ID: 54ed7f070d8e
Revises: aa5362433ff7
Create Date: 2021-05-19 20:57:13.845394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ed7f070d8e'
down_revision = 'aa5362433ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'rental_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
