"""empty message

Revision ID: 6c58fdd17280
Revises: 54ed7f070d8e
Create Date: 2021-05-21 18:42:53.876373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c58fdd17280'
down_revision = '54ed7f070d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('rental_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'rental_id')
    # ### end Alembic commands ###
