"""empty message

Revision ID: f6f973d06101
Revises: 20b20a03caaa
Create Date: 2021-05-21 20:51:12.259167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f973d06101'
down_revision = '20b20a03caaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('returned_on_date', sa.DateTime(), nullable=True))
    op.drop_column('rental', 'checked_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_in', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('rental', 'returned_on_date')
    # ### end Alembic commands ###
