"""empty message

Revision ID: fe5412231ac6
Revises: f6f973d06101
Create Date: 2021-05-27 10:08:16.372586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5412231ac6'
down_revision = 'f6f973d06101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'genre')
    # ### end Alembic commands ###
